
@baseUrl = http://localhost:8080/api/v1
### 1.Simple user want to create a category - must be 403
POST {{baseUrl}}/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk0ODMxNzksImlhdCI6MTc4OTM5Njc3OSwicm9sZSI6ImN1c3RvbWVyIiwic3ViIjoiMmNmYTQ0OGUtOGI4ZC00NmQ1LTk1Y2QtNmRlNzZlY2ZlZDcyIn0.knI0Gc08Pwl9zl7Kc3ugm6Zhwq8PtXD20G0X8SWKMDQ
Content-Type: application/json

{ "name": "Test", "slug": "test" }
### Expected: 403 Forbidden


### 2. Without token must be 401
POST {{baseUrl}}/categories
Content-Type: application/json

{ "name": "Test", "slug": "test" }
### Expected: 401 Unauthorized


### 3.admin creates category must be 201
POST {{baseUrl}}/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODk0ODMxMTUsImlhdCI6MTc4OTM5NjcxNSwicm9sZSI6ImFkbWluIiwic3ViIjoiZTZhMTBmYTQtMDkwYy00NDc0LWJhNzAtZTdmNjNmYjAyZDZiIn0.21dTpEBM_3Q_MbFr-GCP1YYFyqxYtqKV7t3f0FkPm9E
Content-Type: application/json

{ "name": "Electronics", "slug": "electronics" }
### Expected: 201 Created


### 4. GET is public without token
GET {{baseUrl}}/categories
# Expected: 200 OK