
@baseUrl = http://localhost:8080/api/v1
### 1.Simple user want to create a category - must be 403
POST {{baseUrl}}/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTAxMzU3MzMsImlhdCI6MTc5MDA0OTMzMywicm9sZSI6ImN1c3RvbWVyIiwic3ViIjoiMmNmYTQ0OGUtOGI4ZC00NmQ1LTk1Y2QtNmRlNzZlY2ZlZDcyIn0.MWy7-trBXJF0iHfEKvGBAiP8t42zUa5_8-AMfUvJXXY
Content-Type: application/json

{ "name": "Test", "slug": "test" }
### Expected: 403 Forbidden


### 2. Without token must be 401
POST {{baseUrl}}/categories
Content-Type: application/json

{ "name": "Test", "slug": "test" }
### Expected: 401 Unauthorized


### 3.admin creates category must be 201
POST {{baseUrl}}/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTAxMzU1OTIsImlhdCI6MTc5MDA0OTE5Miwicm9sZSI6ImFkbWluIiwic3ViIjoiZTZhMTBmYTQtMDkwYy00NDc0LWJhNzAtZTdmNjNmYjAyZDZiIn0.ENyCGOp-FPmQZVDHgjluN5Qems7kRQszrKjpHxMmrkc
Content-Type: application/json

{ "name": "Electronics", "slug": "electronics" }
### Expected: 201 Created


### 4. GET is public without token
GET {{baseUrl}}/categories
# Expected: 200 OK